services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: concerto-api
    container_name: concerto-api
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - db
    ports:
      - "8000:8000" # expõe a porta do artisan serve
    networks:
      - concerto-network
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: mysql_concerto
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: concerto
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - concerto-network

networks:
  concerto-network:
    driver: bridge

volumes:
  mysql_data:
